# Generated by Django 3.2 on 2023-06-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_auto_20230626_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
