# Generated by Django 3.2 on 2023-06-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_subscribe_subscribing'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='uniqe_user_subscribing',
        ),
    ]
