# Generated by Django 3.2 on 2023-06-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_subscribe_uniqe_user_subscribing'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('user', 'subscribing'), name='uniqe_user_subscribing'),
        ),
    ]
